Update to 3.30
flathub/org.gnome.Photos pull request #5
Opened 2018-10-06 20:15 UTC by uajain

2018-10-06 20:19 UTC, uajain commented
There's a small problem:

Even though there is not changes for the `liboauth` module, I encounter a build failure there as : https://paste.gnome.org/pehehvrqg

I don't get this build failure on master's manifest.

Looking closely, there is an addition `-fstack-protector-strong` flag coming in. I don't see this flag configured while building master's manifest. I don't know from where it's coming from.

@debarshiray Can you take a quick look?

2018-10-07 11:14 UTC, phako commented
See your own history: https://gitlab.gnome.org/GNOME/gnome-photos/commit/886d93bf2542fcddf7b7cae56dee20254e26b945

2018-10-08 12:18 UTC, debarshiray requested changes
By the way, we should also update LibRaw to `0.19.0`.

2018-10-08 12:18 UTC, debarshiray commented on org.gnome.Photos.json
> +                    "url": "https://download.gnome.org/sources/libdazzle/3.30/libdazzle-3.30.0.tar.xz",
Umm... why not go all the way to `3.30.1`?

2018-10-08 12:18 UTC, debarshiray commented on org.gnome.Photos.json
> +                    "url": "https://download.gnome.org/sources/gnome-photos/3.30/gnome-photos-3.30.0.tar.xz",
Ditto about `3.30.1`.

2018-10-08 12:20 UTC, debarshiray commented
I already merged the bit about switching `grilo` to Meson.

Thanks for working on this!

2018-10-08 12:29 UTC, uajain commented
Libraw has a patch in the tree. That's why I didn't touch the modules which requires a patch,

2018-10-08 12:33 UTC, phako commented
The patch applies cleanly to 0.19.0, FWIW

2018-10-08 12:40 UTC, debarshiray commented
Ok, pushed the `LibRaw` update as commit 915519171e2874e6.

2018-10-08 20:29 UTC, nedrichards commented
bot, build

2018-10-09 09:49 UTC, debarshiray commented
> bot, build

Success: https://flathub.org/builds/#/builders/2/builds/5129 !

2018-10-09 09:51 UTC, debarshiray commented
I stuck the URL of this PR in the commit message and merged. Thanks, everybody!

2018-10-09 09:51 UTC, closed without merging